//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppResourceAccess
    {
        public int AppResourceAccess_id { get; set; }
        public int AppResource_id { get; set; }
        public int Identity_id { get; set; }
        public string IdentityType { get; set; }
        public string OperationType { get; set; }
        public string Access { get; set; }
    
        public virtual AppResource AppResource { get; set; }
    }
}
