//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppResource
    {
        public AppResource()
        {
            this.AppResourceAccesses = new HashSet<AppResourceAccess>();
        }
    
        public int AppResource_id { get; set; }
        public string Resource { get; set; }
        public string DefaultAccess { get; set; }
    
        public virtual ICollection<AppResourceAccess> AppResourceAccesses { get; set; }
    }
}
