//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LunchRegister
    {
        public LunchRegister()
        {
            this.UserConsumes = new HashSet<UserConsume>();
        }
    
        public int LunchRegister_id { get; set; }
        public int User_id { get; set; }
        public System.DateTime LunchDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserConsume> UserConsumes { get; set; }
    }
}
