//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FoodCards = new HashSet<FoodCard>();
            this.FoodCardRecharges = new HashSet<FoodCardRecharge>();
            this.FoodCardRecharges1 = new HashSet<FoodCardRecharge>();
            this.LunchRegisters = new HashSet<LunchRegister>();
            this.UserAccounts = new HashSet<UserAccount>();
            this.UserConsumes = new HashSet<UserConsume>();
            this.UserGroupMembers = new HashSet<UserGroupMember>();
        }
    
        public int User_id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<FoodCard> FoodCards { get; set; }
        public virtual ICollection<FoodCardRecharge> FoodCardRecharges { get; set; }
        public virtual ICollection<FoodCardRecharge> FoodCardRecharges1 { get; set; }
        public virtual ICollection<LunchRegister> LunchRegisters { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        public virtual ICollection<UserConsume> UserConsumes { get; set; }
        public virtual ICollection<UserGroupMember> UserGroupMembers { get; set; }
    }
}
