//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunchAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserAccount_id { get; set; }
        public int FoodCard_id { get; set; }
        public int User_id { get; set; }
        public decimal Balance { get; set; }
    
        public virtual FoodCard FoodCard { get; set; }
        public virtual User User { get; set; }
    }
}
